margin = 92
indent = 4
always_for_in = true
whitespace_typedefs = true
whitespace_ops_in_indices = true
whitespace_in_kwargs = false
swparate_kwargs_with_semicolon = true
normalize_line_endings = "unix"
