name: Private Register

on: 
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  register:
    runs-on: ${{ matrix.os }}
    if: github.repository == 'qperfect-io/MimiqCircuits.jl-private'
    strategy:
      matrix:
        julia-version:
          - '1' # latest stable
        julia-arch:
          - x64
        os:
          - ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - run: git config --global user.email "technical@qperfect.io"
      - run: git config --global user.name "QPerfect"

      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}
          arch: ${{ matrix.julia-arch }}

      - uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: |
            ${{ secrets.PRIVATEREGISTRY_KEY }}
            ${{ secrets.MIMIQLINK_KEY }}
            ${{ secrets.MIMIQCIRCUITSBASE_KEY }}

      - name: QPerfect Private Registry
        run: |
          julia -e 'import Pkg; Pkg.update()'
          julia -e 'import Pkg; Pkg.Registry.add(Pkg.RegistrySpec(url = "git@github.com:qperfect-io/QPerfectPrivateRegistry.git"))'
        env:
          JULIA_PKG_USE_CLI_GIT: true

      - name: Register repository
        run: |
          import Pkg
          Pkg.add("LocalRegistry")
          Pkg.develop(path="./")
          using LocalRegistry
          register("MimiqCircuits", registry = "QPerfectPrivateRegistry", repo = "git@github.com:qperfect-io/MimiqCircuits.jl-private.git")
        shell: julia --color=yes {0}
        env:
          JULIA_PKG_USE_CLI_GIT: true
